### ISSUE TITLE
middleware error with readme.md example

### ISSUE THREAD

**Issue by randywreed** [botmasterai/botmaster-watson-conversation-ware#5]
This code from the readme.md errors:
`const { incomingSessionWare, outgoingSessionWare } = SessionWare();
botmaster.useWrapped(incomingSessionWare, outgoingSessionWare);`

Produces error:       throw new Error('useWrapped should be called with both an' +
Error: useWrapped should be called with both an incoming and an outgoing middleware

Perhaps should be updated to match sessionware code?
`const sessionWare = SessionWare();`
`botmaster.useWrapped(sessionWare.incoming, sessionWare.outgoing);`

**Comment by jdwuarin** [comment]
Thanks for pointing that out. You are correct. Updating the readme now with your changes
